#!/usr/bin/env bash
set -euo pipefail

if [[ "${1:-}" != "" ]]; then
  range="$1"
elif [[ "${CI_MERGE_REQUEST_DIFF_BASE_SHA:-}" != "" && "${CI_COMMIT_SHA:-}" != "" ]]; then
  range="${CI_MERGE_REQUEST_DIFF_BASE_SHA}..${CI_COMMIT_SHA}"
elif [[ "${CI_COMMIT_BEFORE_SHA:-}" != "" && "${CI_COMMIT_SHA:-}" != "" && "${CI_COMMIT_BEFORE_SHA}" != "0000000000000000000000000000000000000000" ]]; then
  range="${CI_COMMIT_BEFORE_SHA}..${CI_COMMIT_SHA}"
elif git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
  range="HEAD~1..HEAD"
else
  range="HEAD"
fi
pattern='Co-authored-by:[[:space:]]*(Claude|ChatGPT)|Generated with Claude Code|Generated by[[:space:]].*(AI tool|AI model|Claude|ChatGPT)'

if ! git rev-list "$range" >/dev/null 2>&1; then
  echo "error: invalid git range or revision: $range" >&2
  exit 2
fi

fail=0

while IFS= read -r commit; do
  msg="$(git log -1 --format=%B "$commit")"
  if printf '%s\n' "$msg" | grep -Eiq "$pattern"; then
    subject="$(git log -1 --format=%s "$commit")"
    echo "blocked: banned attribution text found in commit $commit"
    echo "subject: $subject"
    fail=1
  fi
done < <(git rev-list "$range")

if [[ "$fail" -ne 0 ]]; then
  cat <<'EOT'

How to fix:
- Latest commit:
  git commit --amend
  # remove the attribution lines, save, then push
  git push --force-with-lease

- Older commits:
  git rebase -i <base-commit>
  # mark commit as reword or edit, remove attribution lines
  git rebase --continue
  git push --force-with-lease
EOT
  exit 1
fi

echo "ok: no banned AI attribution lines found in range '$range'"
